apiVersion: v1
kind: Service
metadata:
  name: dustboard
  labels:
    app: dust-train
spec:
  selector:
    app: dust-train
  ports:
    - protocol: TCP
      port: 6006
      targetPort: dustboard-port
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tensorboard
  annotations:
    # using kubernetes/ingress-nginx controller
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /

    # SSL
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"

    # websocket
    nginx.ingress.kubernetes.io/proxy-send-timeout: "86400"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"

spec:
  tls:
    - hosts:
        - dusttrain.c.videogorillas.com
      secretName: tls-secret

  rules:
    - host: dusttrain.c.videogorillas.com
      http:
        paths:
          - backend:
              serviceName: dustboard
              servicePort: dustboard-port

---
apiVersion: batch/v1
kind: Job
metadata:
  name: train-dust
spec:
  backoffLimit: 0
  parallelism: 1
  template:
    metadata:
      labels:
        app: dust-train
    spec:
      imagePullSecrets:
        - name: regcred
      restartPolicy: Never
      containers:
        - image: blender.local:5000/dustinpaint:latest
          imagePullPolicy: IfNotPresent
          name: dust
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /svlk
              name: svlk-volume
            - mountPath: /storage
              name: storage-volume
          command:
            - python
            - train.py
            - "--root"
            - "/storage/clients/uk/dustdataset/256.clean"
            - "--mask_root"
            - "/storage/clients/uk/dustdataset/256.8bit"
            - "--vis_interval"
            - "100"
            - "--masks_csv"
            - "/storage/clients/uk/dustdataset/selected_patches.csv"
            - "--save_dir"
            - "/svlk/dusttrain/snapshots/default"
            - "--log_dir"
            - "/svlk/dusttrain/logs/default"
            - "--resume"
            - "/svlk/dusttrain/snapshots/1m.pth"
          resources:
            limits:
              nvidia.com/gpu: 1
        - image: blender.local:5000/dustinpaint:latest
          imagePullPolicy: IfNotPresent
          name: dustboard
          volumeMounts:
            - mountPath: /svlk
              name: svlk-volume
          command:
            - "tensorboard"
            - "--logdir"
            - "/svlk/dusttrain/logs"
          ports:
            - containerPort: 6006
              hostPort: 6006
              name: dustboard-port


      nodeSelector:
        #        feature.node.kubernetes.io/gfd-nvidia-memory: "24449"
        #        feature.node.kubernetes.io/gfd-nvidia-memory: "8117"

        #        feature.node.kubernetes.io/gfd-nvidia-model: Tesla-K80
        # feature.node.kubernetes.io/gfd-nvidia-model: GeForce-GTX-1070
        feature.node.videogorillas.com/storage-speed: "10" #10gbe or direct access
        #        feature.node.kubernetes.io/gfd-nvidia-model: Quadro-P6000


      volumes:
        - name: dshm
          emptyDir:
            medium: Memory

        - name: svlk-volume
          hostPath:
            # directory location on host
            path: /svlk
            # this field is optional
            type: Directory

        - name: storage-volume
          hostPath:
            # directory location on host
            path: /storage
            # this field is optional
            type: Directory
